# Site settings
title: Eddie Vaisman
email: eddie.vaisman@gmail.com
description: "Eddie Vaisman"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eddievaisman.com" # the base hostname & protocol for your site
twitter_username: EddieVaisman
github_username:  EVaisman
permalinks: /:title
# Build settings
markdown: kramdown
